name: Lint CloudFormation Templates

on: [push]

jobs:
  cloudformation-linter:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: cfn-lint
        uses: scottbrenner/cfn-lint-action@master
        with:
          args: "CloudFormation/*.yaml"
